services:
  - type: web
    name: aeon
    image:
      url: docker.io/abkmhr12/aeon:latest
    plan: starter
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DEBUG
        value: False
      - key: LOG_LEVEL
        value: INFO
      - key: ARTIFACTS_DIR
        value: /app/artifacts
