# Generated by Django 6.0.3 on 2026-03-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="section",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(default="", max_length=500, unique=True),
        ),
    ]
