# Generated by Django 6.0.3 on 2026-03-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_article_image_url_article_section_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="article",
            name="section",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
