# Generated by Django 6.0.3 on 2026-03-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_alter_article_author_alter_article_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
